test: add normal/try catch revert testcase
godwokenrises/godwoken-polyjuice pull request #183
Opened 2022-10-26 04:35 UTC by RetricSu

2022-10-26 05:19 UTC, magicalne approved these changes
The build failed as just we can expect.

2022-10-27 12:03 UTC, keroro520 requested changes

2022-10-28 05:17 UTC, RetricSu commented on polyjuice-tests/src/test_cases/evm-contracts/revert/contracts.sol
> +contract DebugAAA {
any suggestions for the name? contract A / B / C ?

2022-10-28 06:41 UTC, keroro520 commented on polyjuice-tests/src/test_cases/evm-contracts/revert/contracts.sol
> +contract DebugAAA {
We can learn naming from this directory https://github.com/ethereum/tests/tree/develop/GeneralStateTests/stRevertTest

2022-11-01 15:01 UTC, RetricSu commented on polyjuice-tests/src/test_cases/evm-contracts/revert/contracts.sol
> +contract DebugAAA {
updated

2022-11-01 15:05 UTC, RetricSu commented
commit [f21f29f](https://github.com/godwokenrises/godwoken-polyjuice/pull/183/commits/f21f29f9e5c2711c88dd77a62aeb6638b9eeb4cf) 

- rename test contracts for better maintainbility
- covert try catch revert test in contract constructor

2022-11-02 02:25 UTC, magicalne approved these changes

2022-11-02 07:05 UTC, keroro520 commented on polyjuice-tests/src/test_cases/evm-contracts/revert/CallRevertWithTryCatch.json
> +  "sourceName": "contracts/try.sol",
should we update "sourceName"? and abi description.

2022-11-02 07:05 UTC, keroro520 approved these changes

2022-11-02 07:15 UTC, Flouse approved these changes

2022-11-02 08:21 UTC, merged