Enable try-catch feature
godwokenrises/godwoken-polyjuice pull request #184
Opened 2022-11-02 12:51 UTC by magicalne

Some test cases failed.

Reproduce: 
```sh
cd polyjuice-tests
RUST_LOG=gw_generator=debug cargo test --lib -- test_cases::call_multiple_times::test_call_multiple_times --nocapture
```

2022-11-04 08:02 UTC, jjyr requested changes

2022-11-04 08:38 UTC, magicalne commented on c/polyjuice.h
> +    res.status_code = (evmc_status_code)ret;
done

2022-11-04 08:38 UTC, magicalne commented on c/polyjuice.h
> +    res.status_code = EVMC_SUCCESS;
done

2022-11-04 09:19 UTC, jjyr requested changes

2022-11-04 09:19 UTC, jjyr commented on c/polyjuice.h
> +      if (ret != 0) {
Duplicated condition.

2022-11-04 09:19 UTC, jjyr commented on c/polyjuice.h
> +        if (is_fatal_error(revert_ret)) {
Duplicated

2022-11-04 10:36 UTC, jjyr approved these changes

2022-11-04 12:32 UTC, zeroqn approved these changes

2022-11-04 12:44 UTC, RetricSu approved these changes

2022-11-06 05:01 UTC, Flouse approved these changes

2022-11-06 05:33 UTC, merged